import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const webRoot = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(webRoot, "..");
const generatedPath = resolve(projectRoot, "server/ui/generated/widgets.mjs");
const styles = await readFile(resolve(webRoot, "src/styles.css"), "utf8");

const widgets = [
  { exportName: "itineraryWidgetHtml", entry: "src/itinerary/index.jsx" },
  { exportName: "tripIntakeWidgetHtml", entry: "src/intake/index.jsx" },
  { exportName: "tripListWidgetHtml", entry: "src/trips/index.jsx" },
  { exportName: "tripRequirementsWidgetHtml", entry: "src/requirements/index.jsx" },
  { exportName: "publicShareControlWidgetHtml", entry: "src/share-control/index.jsx" },
];

const pages = [
  { exportName: "publicSharePageHtml", entry: "src/share/index.jsx" },
];

function safeInlineScript(source) {
  return source.replaceAll("</script", "<\\/script");
}

async function bundleWidget(entry) {
  const result = await build({
    entryPoints: [resolve(webRoot, entry)],
    bundle: true,
    format: "iife",
    jsx: "automatic",
    minify: true,
    target: ["es2020"],
    write: false,
    define: { "process.env.NODE_ENV": '"production"' },
  });
  const javascript = result.outputFiles.find((file) => file.path.endsWith(".js")) || result.outputFiles[0];
  if (!javascript) throw new Error(`No JavaScript output generated for ${entry}`);
  return `<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>${styles}</style>
  </head>
  <body>
    <div id="root"></div>
    <script>${safeInlineScript(javascript.text)}</script>
  </body>
</html>`;
}

const outputs = [];
for (const app of [...widgets, ...pages]) {
  outputs.push({ ...app, html: await bundleWidget(app.entry) });
}

const generated = [
  "// Generated by npm run build:ui. Edit web/src instead.",
  ...outputs.map(({ exportName, html }) => `export const ${exportName} = ${JSON.stringify(html)};`),
  "",
].join("\n");

await mkdir(dirname(generatedPath), { recursive: true });
await writeFile(generatedPath, generated);
console.log(`Built ${widgets.length} Sendero UI components and ${pages.length} public page.`);
